module toml::parser;

import std::io;
import std::collections::object;
import std::collections::list;

alias StringList = List {String};
alias TableList  = List {Object*};

faultdef DUPLICATED_KEY,
	DUPLICATED_TABLE,
	INVALID_BOOLEAN,
	INVALID_DATETIME,
	INVALID_QUOTE,
	INVALID_TERMINAL_QUOTES,
	INVALID_ESCAPE_UNICODE,
	INVALID_ESCAPE_SEQUENCE,
	INVALID_TOKEN_TYPE,
	INVALID_UNICODE,
	INVALID_NON_ASCII,
	INVALID_UNDERSCORE,
	INVALID_SCALAR_UNICODE,
 	INVALID_LINE_ENDING_BACKSLASH,
	INVALID_TABLE,
	INVALID_ARRAY_TABLE,
	INVALID_ARRAY,
	INVALID_KEY,
 	INVALID_LEADING_ZERO,
	INVALID_COMMA,
	INVALID_LITERAL,
	INVALID_STRING,
	INVALID_NEWLINE,
	UNCLOSED_INLINE_TABLE,
	UNCLOSED_STD_TABLE,
	UNCLOSED_ARRAY_TABLE,
	UNCLOSED_QUOTE,
	UNCLOSED_MULTILINE,
	MISSING_KEYVAL_SEPARATOR,
	MISSING_TABLE_NAME,
	MISSING_TERMINAL_QUOTE,
	MISSING_NEWLINE,
	MISSING_COMMA,
	MULTILINE_STRING_TOO_SHORT,
	UNMUTABLE_INLINE_TABLES,
	UNSIGNED_WITH_SIGN,
	MULTIPLE_ERRORS;

struct Parser
{
	String s;
	Allocator allocator;
	usz start;
	usz current;
	usz line, column;
	Object* current_table;
	TableList explicit_tables;
	TableList implicit_tables;
	TableList inline_tables;
	TableList array_of_tables;
	bool verbose;
}

fn Parser* Parser.init(&self, String s, Allocator allocator, bool verbose = true)
{
	*self = {.s = s, .allocator = allocator, .start = 0, .current = 0,
		.line = 1, .column = 1, .current_table = null, .verbose = verbose};
	return self;
}

fn char? Parser.advance(&self)
{
	if (self.at_end()) return io::EOF~;
	if (self.peek() == '\n')
	{
		self.line++;
		self.column = 1;
	}
	else
	{
		self.column++;
	}
	return self.s[self.current++];
}

fn char Parser.peek(&self)
{
	if (self.at_end()) return '\0';
	return self.s[self.current];
}

fn bool Parser.at_end(&self)
{
	return self.current >= self.s.len;
}

fn void Parser.report_error(&self, String msg, bool full_report = false)
{
	iptr start, end;

	if (!self.verbose) return;

	io::eprintfn("TOML ERROR -- Line %d, Col %d: %s", self.line, self.column, msg)!!;

	if (full_report)
	{
		start = (iptr)(self.current - self.column + 1);
		if (start < 0 || start >= self.s.len) return;

		end = (iptr)(self.s.len - 1);
		if (try index = self.s[start .. ].index_of_char('\n')) end = start + index;

		io::eprintn(self.s[start .. end].trim_right());
		if (self.column > 0) io::eprintfn("%*s^", self.column - 1, "");
	}
}

fn bool is_ws(char c) => (c == 0x20 || c == 0x09);


// newline =  x0A     ; LF
// newline =/ x0D.0A  ; CRLF
// fn bool is_newline(char c) => (c == 0x0A || c == 0x0D);
fn bool is_lf(char c) => c == 0x0A;

// if CR, then a LF must follow!
fn bool is_cr(char c) => c == 0x0D;

// incomplete implementation of non_ascii; you still not to verify that the
// actual codepoint is a scalar unicode
fn bool non_ascii(char c) => (c >= 0x80);

// Note that the specs says that 0x7f should be allowed as non-eol; but the
// tomltest suite records it as invalid; follow the testsuite.
fn bool non_eol(char c)
{
	return (c == 0x09 || (c >= 0x20 && c < 0x7F) || non_ascii(c));
}

fn bool is_unquoted_key(char c)
{
	return (c.is_alpha() || c.is_digit() || c == '-' || c == '_');
}

fn void? Parser.skip_ws(&self)
{
	while (is_ws(self.peek())) self.advance()!;

	self.start = self.current;
}

// comment = comment-start-symbol *non-eol
// comment-start-symboel = #
// non-eol =  0x09 / 0x20 - 0x7f / non-ascii
// non-ascii = 0x80 - D7FF/ 0xE000 - 10FFFF
fn void? Parser.skip_comment(&self)
{
	if (!self.must('#')) return;

	char c;
	while (non_eol(c = self.peek()))
	{
		// non-ascii
		if (is_unicode(c))
		{
			Char32 codepoint = self.scan_unicode()!;
			if (!is_non_ascii(codepoint)) return INVALID_NON_ASCII~;
		}
		// non-eol
		else
		{
			self.advance()!;
		}
	}
}

// sw-comment-newline = *( wschar / [comment ] newline )
fn void? Parser.skip_ws_comment_newline(&self)
{
	while LOOP: (1)
	{
		char c = self.peek();
		switch
		{
			case is_ws(c):
				self.skip_ws()!;
			case c == '#':
				self.skip_comment()!;
			case is_lf(c):
				self.advance()!;
			case is_cr(c):
				self.advance()!;
				if (!is_lf(self.peek())) return INVALID_NEWLINE~;
				self.advance()!;
			default:
				break LOOP;
		}
	}
}

fn String Parser.text(&self)
{
	return self.s[self.start..self.current-1];
}

fn bool Parser.must(&self, char c)
{
	if (self.peek() != c) return false;

	(void)self.advance();

	return true;
}

fn bool? Parser.match(&self, String str)
{
	usz backup = self.current;

	foreach (s : str)
	{
		if (!self.must(s))
		{
			self.current = backup;
			return false;
		}
	}

	return true;
}

fn Object*? Parser.boolean(&self)
{
	bool value;

	if (self.match("true")!)
	{
		value = true;
	}
	else if (self.match("false")!)
	{
		value = false;
	}
	else
	{
		self.report_error("could not parse boolean; did you misspell 'true' or 'false'");
		return INVALID_BOOLEAN~;
	}

	return object::new_bool(value);
}

// inline-table = inline-table-open [ inline-table-keyvals ] inline-table-close
// inline-table-open = '{' ws
// inline-table-close = ws '}'
// inline-table-sep = ws ',' ws
// inline-table-keyvals = keyval [ inline-table-sep inline-table-keyvals ]
fn Object*? Parser.inline_table(&self)
{
	self.must('{');

	self.skip_ws()!;

	if (self.peek() == ',') return INVALID_COMMA~;

	Object* table = object::new_obj(self.allocator);
	while INLINE_TABLE: (1)
	{
		self.keyval(table)!;

		// Read inline-table-sep
		self.skip_ws()!;

		if (self.must(','))
		{
			self.skip_ws()!;
			switch (self.peek())
			{
			case ',':
			case '}':
				return INVALID_COMMA~;
			}
			continue;
		}

		break INLINE_TABLE;
	}

	if (!self.must('}'))
	{
		self.report_error("expected '}'");
		return UNCLOSED_INLINE_TABLE~;
	}

	// Store inline table
	self.inline_tables.push(table);

	return table;
}

fn Object*? Parser.value(&self)
{
	switch (self.peek())
	{
		case '"':
		case '\'':
			return self.string()!;
		case 't':
		case 'f':
			return self.boolean()!;
		case '[':
			return self.array();
		case '{':
			return self.inline_table();
		default:
			return self.number_or_datetime();
	}
}

// key = simple-key / dotted-key
// simple-key = quoted-key / unquoted-key
//
// unquoted-key = 1*( ALPHA / DIGIT / 0x2d / 0x5F); A-Z / a-z / 0-9 / - / _
// quoted-key = basic-string / literal-string
// dotted-key = simple-key 1*( dot-sep simple-key )
//
// Returns true when keys were parsed.
fn bool? Parser.key(&self, StringList *list)
{
	String text;
	Object *s;

	while (1)
	{
		self.skip_ws()!;

		if (self.must('"'))
		{
			// quoted-key: basic-string
			s = self.basic_string()!;
			list.push(s.s.copy(list.allocator));
			s.free();
		}
		else if (self.must('\''))
		{
			// quoted-key: literal-string
			s = self.literal_string()!;
			list.push(s.s.copy(list.allocator));
			s.free();
		}
		else
		{
			self.start = self.current;

			// unquoted-key
			while (is_unquoted_key(self.peek())) self.advance()!;

			if (self.current <= self.start) return !list.is_empty();

			list.push(self.text().copy(list.allocator));
		}

		self.skip_ws()!;

		if (!self.must('.')) return !list.is_empty();
	}
}

fn void? Parser.insert(&self, Object *table, StringList k, Object* v)
{
	String key = k.pop()!;
	Object* target = self.create_table(k, table, false, true)!;
	if (!target.is_keyable())
	{
		self.report_error("key does not point to a table");
		return INVALID_KEY~;
	}
	if (target.has_key(key))
	{
		self.report_error("key is already used; duplicated keys are not supported.");
		return DUPLICATED_KEY~;
	}
	else if (self.inline_tables.contains(target))
	{
		self.report_error("keys cannot be added to inline tables outside the braces");
		return UNMUTABLE_INLINE_TABLES~;
	}
	else if (self.array_of_tables.contains(target))
	{
		self.report_error("keys cannot be added to array of tables");
		return UNMUTABLE_INLINE_TABLES~;
	}
	target.set(key, v);
}

// keyval = key keyval-sep val
// keyval-sep = ws '=' ws
fn void? Parser.keyval(&self, Object *current_table) => @pool()
{
	StringList key;
	key.tinit(4);

	// parse key
	if (!self.key(&key)!) return;

	// consume ws '=' ws
	self.skip_ws()!;
	if (!self.must('='))
	{
		self.report_error("expected '='");
		return MISSING_KEYVAL_SEPARATOR~;
	}
	self.skip_ws()!;

	// parse value
	Object* val = self.value()!;

	self.insert(current_table, key, val)!;
}

fn Object*? Parser.get_table(&self, StringList tables, Object *cur)
{
	foreach(table : tables)
	{
		if (!cur.is_keyable()) return INVALID_TABLE~;
		cur = cur.get(table)!;
	}
	return cur;
}

fn Object*? Parser.create_table(&self, StringList tables, Object *cur, bool array_of_table, bool save_implicit)
{
	foreach(table : tables)
	{
		if (!cur.is_keyable())
		{
			if (cur.is_array())
			{
				cur = cur.get_at(cur.get_len()-1);
			}
			else
			{
				return INVALID_TABLE~;
			}

		}

		if (self.inline_tables.contains(cur))
		{
			self.report_error("keys cannot be added to inline tables outside the braces");
			return UNMUTABLE_INLINE_TABLES~;
		}

		cur = cur.get_or_create_obj(table);

		if (save_implicit)
		{

			if (!self.implicit_tables.contains(cur))
			{
				self.implicit_tables.push(cur);
			}

			if (self.explicit_tables.contains(cur))
			{
				self.report_error("table is already defined explicitly");
				return INVALID_TABLE~;
			}

		}
	}

	if (array_of_table) {

		if (!cur.is_indexable())
		{
			return INVALID_ARRAY_TABLE~;
		}

		if (cur.get_len() == 0)
		{
			self.array_of_tables.push(cur);
		}

		cur.push_object(object::new_obj(self.allocator));

		return cur.get_at(cur.get_len()-1);
	}

	return cur;
}

// table = std-table / array-table
//
// std-table = std-table-open key std-table-close
//
// std-table-open = '[' ws
// std-table-close = ws ']'
//
// array-table = array-table-open key array-table-close
//
// array-table-open = '[[' ws
// array-table-close = ws ']]' ws
fn Object*? Parser.table(&self, Object *obj) => @pool()
{
	self.must('[');

	bool array_of_table = self.must('[');

	self.skip_ws()!;

	StringList key;
	key.tinit(4);

	if (!self.key(&key)!)
	{
		self.report_error("you must specify a table name between [ and ]");
		return MISSING_TABLE_NAME~;
	}

	// Verfiy that table does not exist yet
	if (try tab = self.get_table(key, obj))
	{
		if (array_of_table)
		{
			// Array table already exists and now check that it
			// actually is an array (is_indexable())
			if (!tab.is_array()) return INVALID_ARRAY_TABLE~;

			// Array should be in the array_of_tables list
			if (!self.array_of_tables.contains(tab)) return INVALID_ARRAY_TABLE~;
		}
		else
		{
			// Regular table already exists as an implicit table
			if (self.implicit_tables.contains(tab))
			{
				self.report_error("table already exists (implicitly defined)");
				return DUPLICATED_TABLE~;
			}

			// Cannot have two explicitly defined tables either
			if (self.explicit_tables.contains(tab))
			{
				self.report_error("table already exists (explicitly defined)");
				return DUPLICATED_TABLE~;
			}

			// Cannot conflict with an array of tables
			if (self.array_of_tables.contains(tab))
			{
				self.report_error("table already exists (array of tables)");
				return DUPLICATED_TABLE~;
			}
		}
	}

	Object *cur = self.create_table(key, obj, array_of_table, false)!;

	self.skip_ws()!;

	if (!self.must(']')) {
		self.report_error("expected ']'; did you forget to add the closing bracket ']'?");
		return UNCLOSED_STD_TABLE~;
	}

	if (array_of_table && !self.must(']')) {
		self.report_error("expected ']]'; did you forget to add an additonal ']'?");
		return UNCLOSED_ARRAY_TABLE~;
	}

	if (!array_of_table) self.explicit_tables.push(cur);

	return cur;
}

// expression =  ws [ comment ]
// expression =/ ws keyval ws [ comment ]
// expression =/ ws table ws [ comment ]
fn void? Parser.expression(&self, Object *obj)
{
	self.skip_ws()!;
	self.skip_comment()!;

	if (self.peek() == '[')
	{
		self.current_table = self.table(obj)!;
	}
	else
	{
		self.keyval(self.current_table)!;
	}


	self.skip_ws()!;
	self.skip_comment()!;
}

// toml = expression *( newline expression )
// newline =  0x0A
// newline =/ 0x0D.0x0A
fn Object*? Parser.toml(&self) => @pool()
{
	Object* root = object::new_obj(self.allocator);
	self.current_table = root;

	self.explicit_tables.tinit();
	self.implicit_tables.tinit();
	self.inline_tables.tinit();
	self.array_of_tables.tinit();

	fault last_error;
	int max_lines = int::max;
	while LOOP: (max_lines--) {
		if (catch err = self.expression(root))
		{
			if (err == io::EOF) break LOOP;

			self.report_error(string::tformat("%s", err), true);

			last_error = last_error ? MULTIPLE_ERRORS : err;

			// synchronize parser after error by moving to the next
			// newline.
			while (non_eol(self.peek()))
			{
				if (catch adv_err = self.advance())
				{
					if (adv_err == io::EOF) break LOOP;
				}
			}
		}

		if (self.must('\r'))
		{
			if (self.at_end() || self.peek() != '\n')
			{
				self.report_error("Bare CR are not allowed.", true);
				return MISSING_NEWLINE~;
			}
		}

		if (!self.must('\n'))
		{
			if (self.at_end()) break LOOP;
			io::printfn("remaining: %s", (String)self.s[self.current ..]);
			self.report_error("Missing Newline after an expression", true);
			return MISSING_NEWLINE~;
		}
	}

	// If en error has been encountered, return it
	if (last_error) return last_error~;

	return root;
}

